// <auto-generated />
using System;
using Documentify.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Documentify.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUserOfficeSuggestion", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UpvotedOfficeSuggestionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationUserId", "UpvotedOfficeSuggestionsId");

                    b.HasIndex("UpvotedOfficeSuggestionsId");

                    b.ToTable("UserOfficeSuggestionUpvotes", (string)null);
                });

            modelBuilder.Entity("ApplicationUserServiceSuggestion", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UpvotedServiceSuggestionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationUserId", "UpvotedServiceSuggestionsId");

                    b.HasIndex("UpvotedServiceSuggestionsId");

                    b.ToTable("UserServiceSuggestionUpvotes", (string)null);
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Common.OfficeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<TimeOnly?>("EveningOpenFrom")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("EveningOpenTo")
                        .HasColumnType("time");

                    b.Property<bool>("Is24_7")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double?>("LocationLat")
                        .HasColumnType("float");

                    b.Property<double?>("LocationLng")
                        .HasColumnType("float");

                    b.Property<string>("LocationText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly?>("OpenFrom")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("OpenTo")
                        .HasColumnType("time");

                    b.Property<string>("Phones")
                        .HasMaxLength(165)
                        .HasColumnType("nvarchar(165)");

                    b.Property<byte?>("Workdays")
                        .HasColumnType("tinyint");

                    b.Property<string>("WriterId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WriterId");

                    b.ToTable("OfficeBase", (string)null);

                    b.HasDiscriminator().HasValue("OfficeBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Common.ServiceBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(11, 2)
                        .HasColumnType("decimal(11,2)");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailableOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WriterId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("WriterId");

                    b.ToTable("ServiceBase", (string)null);

                    b.HasDiscriminator().HasValue("ServiceBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Documentify.Domain.Entities.OfficeStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("OfficeStatus", (string)null);
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Step", b =>
                {
                    b.Property<Guid>("AssociatedServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<decimal>("CostRequired")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Details")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("InnerServiceCountCopies")
                        .HasColumnType("int");

                    b.Property<int?>("InnerServiceCountOriginals")
                        .HasColumnType("int");

                    b.Property<Guid?>("InnerServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimeRequired")
                        .HasColumnType("int");

                    b.HasKey("AssociatedServiceId", "Order");

                    b.HasIndex("InnerServiceId");

                    b.ToTable("Steps", (string)null);
                });

            modelBuilder.Entity("Documentify.Domain.Entities.UserRateOffice", b =>
                {
                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RaterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.HasKey("OfficeId", "RaterId");

                    b.HasIndex("RaterId");

                    b.ToTable("UserRateOffice", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ServiceOfficeAvailability", b =>
                {
                    b.Property<Guid>("OfficesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServicesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OfficesId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ServiceOfficeAvailability", (string)null);
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Office", b =>
                {
                    b.HasBaseType("Documentify.Domain.Entities.Common.OfficeBase");

                    b.Property<string>("ApproverId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("ApproverId");

                    b.HasDiscriminator().HasValue("Office");
                });

            modelBuilder.Entity("Documentify.Domain.Entities.OfficeSuggestion", b =>
                {
                    b.HasBaseType("Documentify.Domain.Entities.Common.OfficeBase");

                    b.Property<string>("Change")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("OfficeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SuggestionType")
                        .HasColumnType("int");

                    b.HasIndex("OfficeId");

                    b.HasDiscriminator().HasValue("OfficeSuggestion");
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Service", b =>
                {
                    b.HasBaseType("Documentify.Domain.Entities.Common.ServiceBase");

                    b.Property<string>("ApproverId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("ApproverId");

                    b.HasDiscriminator().HasValue("Service");
                });

            modelBuilder.Entity("Documentify.Domain.Entities.ServiceSuggestion", b =>
                {
                    b.HasBaseType("Documentify.Domain.Entities.Common.ServiceBase");

                    b.Property<string>("Change")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SuggestionType")
                        .HasColumnType("int");

                    b.HasIndex("ServiceId");

                    b.HasDiscriminator().HasValue("ServiceSuggestion");
                });

            modelBuilder.Entity("Documentify.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("ApplicationUserOfficeSuggestion", b =>
                {
                    b.HasOne("Documentify.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Documentify.Domain.Entities.OfficeSuggestion", null)
                        .WithMany()
                        .HasForeignKey("UpvotedOfficeSuggestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationUserServiceSuggestion", b =>
                {
                    b.HasOne("Documentify.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Documentify.Domain.Entities.ServiceSuggestion", null)
                        .WithMany()
                        .HasForeignKey("UpvotedServiceSuggestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Common.OfficeBase", b =>
                {
                    b.HasOne("Documentify.Infrastructure.Data.ApplicationUser", null)
                        .WithMany("OfficesWritten")
                        .HasForeignKey("WriterId");
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Common.ServiceBase", b =>
                {
                    b.HasOne("Documentify.Domain.Entities.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Documentify.Infrastructure.Data.ApplicationUser", null)
                        .WithMany("ServicesWritten")
                        .HasForeignKey("WriterId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Documentify.Domain.Entities.OfficeStatus", b =>
                {
                    b.HasOne("Documentify.Domain.Entities.Office", "Office")
                        .WithMany("OfficeStatuses")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Step", b =>
                {
                    b.HasOne("Documentify.Domain.Entities.Common.ServiceBase", "AssociatedService")
                        .WithMany("Steps")
                        .HasForeignKey("AssociatedServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Documentify.Domain.Entities.Common.ServiceBase", "InnerService")
                        .WithMany()
                        .HasForeignKey("InnerServiceId");

                    b.Navigation("AssociatedService");

                    b.Navigation("InnerService");
                });

            modelBuilder.Entity("Documentify.Domain.Entities.UserRateOffice", b =>
                {
                    b.HasOne("Documentify.Domain.Entities.Office", "Office")
                        .WithMany("UserRateOffices")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Documentify.Infrastructure.Data.ApplicationUser", null)
                        .WithMany("UserRateOffices")
                        .HasForeignKey("RaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceOfficeAvailability", b =>
                {
                    b.HasOne("Documentify.Domain.Entities.Common.OfficeBase", null)
                        .WithMany()
                        .HasForeignKey("OfficesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Documentify.Domain.Entities.Common.ServiceBase", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Office", b =>
                {
                    b.HasOne("Documentify.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Documentify.Domain.Entities.OfficeSuggestion", b =>
                {
                    b.HasOne("Documentify.Domain.Entities.Office", "Office")
                        .WithMany("OfficeSuggestions")
                        .HasForeignKey("OfficeId");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Service", b =>
                {
                    b.HasOne("Documentify.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Documentify.Domain.Entities.ServiceSuggestion", b =>
                {
                    b.HasOne("Documentify.Domain.Entities.Service", "Service")
                        .WithMany("ServiceSuggestions")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Common.ServiceBase", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Office", b =>
                {
                    b.Navigation("OfficeStatuses");

                    b.Navigation("OfficeSuggestions");

                    b.Navigation("UserRateOffices");
                });

            modelBuilder.Entity("Documentify.Domain.Entities.Service", b =>
                {
                    b.Navigation("ServiceSuggestions");
                });

            modelBuilder.Entity("Documentify.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.Navigation("OfficesWritten");

                    b.Navigation("ServicesWritten");

                    b.Navigation("UserRateOffices");
                });
#pragma warning restore 612, 618
        }
    }
}
